print("\nComparison of Supervised and Unsupervised Learning\n")
print("1. Supervised Learning:")
print("   - Uses labeled data (input-output pairs).")
print("   - Goal: Predict output for new inputs.")
print("   - Common Tasks: Classification, Regression.")
print("   - Examples: Linear Regression, SVM, Random Forest.")
print("\n2. Unsupervised Learning:")
print("   - Uses unlabeled data (only inputs).")
print("   - Goal: Find hidden structures or patterns in data.")
print("   - Common Tasks: Clustering, Dimensionality Reduction.")
print("   - Examples: K-Means, PCA, Hierarchical Clustering.")
print("\nSummary: Supervised learning requires supervision (labels) to train, while unsupervised learning discovers patterns independently.")
