print("\nCNN on MNIST Dataset\n")
print("import tensorflow as tf")
print("from tensorflow.keras import layers, models")
print("(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()")
print("x_train, x_test = x_train / 255.0, x_test / 255.0")
print("x_train = x_train[..., tf.newaxis]")
print("x_test = x_test[..., tf.newaxis]")
print("model = models.Sequential([")
print("    layers.Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(28, 28, 1)),")
print("    layers.MaxPooling2D((2, 2)),")
print("    layers.Dropout(0.2),")
print("    layers.Conv2D(64, (3, 3), padding='same', activation='relu'),")
print("    layers.MaxPooling2D((2, 2)),")
print("    layers.Flatten(),")
print("    layers.Dense(10, activation='softmax')")
print("])")
print("opt = tf.keras.optimizers.Adam(learning_rate=0.01)")
print("model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['accuracy'])")
print("print('Model compiled successfully with given constraints.')")
