print("\nCNN for Image Recognition (Orange vs Apple)\n")
print("import tensorflow as tf")
print("from tensorflow.keras import layers, models")
print("model = models.Sequential([")
print("    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)),")
print("    layers.MaxPooling2D((2, 2)),")
print("    layers.Flatten(),")
print("    layers.Dense(64, activation='relu'),")
print("    layers.Dense(1, activation='sigmoid') # Binary classification")
print("])")
print("model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])")
print("print('CNN model constructed successfully.')")
