print("\nCNN for Object Detection (Person, Car, Dog)\n")
print("model = models.Sequential([")
print("    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),")
print("    layers.MaxPooling2D((2, 2)),")
print("    layers.Flatten(),")
print("    layers.Dense(128, activation='relu'),")
print("    layers.Dense(3, activation='softmax') # 3 classes")
print("])")
print("print('CNN for multiclass object detection defined.')")
